"apt-get -y install sudo" --> no sudo in bionic container

"sudo apt-get install -y software-properties-common"  --> otherwise no "sudo add-apt-repository universe"

"sudo apt-get install wget" --> no wget in bionic container

***
no RUN -> wsman missing error similar to https://github.com/christophwille/pscore-playground/issues/1 (Mac issue)